#!/bin/bash

PATH=/bin:/usr/bin:/usr/local/bin

DOCKER_VERSION=$(docker version)
DOCKER_INFO=$(docker info)

STORAGE_DRIVER=$(echo "$DOCKER_INFO" | grep Storage\ Driver | awk '{print $NF}')
VERSION=$(echo "$DOCKER_VERSION" | grep Version | head -n 1  | awk '{print $2}')

COMMERCIAL_TYPE=$(scw-metadata --cached COMMERCIAL_TYPE)

cat <<EOF

Docker $VERSION is running using the '$STORAGE_DRIVER' storage driver.
Installed tools: docker-compose, nsenter, gosu and pipework are installed.
EOF

if [ "$COMMERCIAL_TYPE" = "C1" ]; then
    echo "Getting started with Docker on C1: https://community.cloud.online.net/t/383?u=manfred."
fi
